#ifndef ASCIISYMBOLMAP_H
#define ASCIISYMBOLMAP_H

symbol_t symbolAsciiMap[128] = {
	/*   0   */ SYMBOL_EMPTY,
	/*   1  */ SYMBOL_EMPTY,
	/*   2  */ SYMBOL_EMPTY,
	/*   3  */ SYMBOL_EMPTY,
	/*   4  */ SYMBOL_EMPTY,
	/*   5   */ SYMBOL_EMPTY,
	/*   6  */ SYMBOL_EMPTY,
	/*   7   */ SYMBOL_EMPTY,
	/*   8   */ SYMBOL_EMPTY,
	/*   9 	 */ SYMBOL_EMPTY,
	/*  10   */ SYMBOL_EMPTY,
	/*  11   */ SYMBOL_EMPTY,
	/*  12   */ SYMBOL_EMPTY,
	/*  13   */ SYMBOL_EMPTY,
	/*  14   */ SYMBOL_EMPTY,
	/*  15   */ SYMBOL_EMPTY,
	/*  16  */ SYMBOL_EMPTY,
	/*  17  */ SYMBOL_EMPTY,
	/*  18  */ SYMBOL_EMPTY,
	/*  19  */ SYMBOL_EMPTY,
	/*  20  */ SYMBOL_EMPTY,
	/*  21  */ SYMBOL_EMPTY,
	/*  22  */ SYMBOL_EMPTY,
	/*  23  */ SYMBOL_EMPTY,
	/*  24  */ SYMBOL_EMPTY,
	/*  25  */ SYMBOL_EMPTY,
	/*  26  */ SYMBOL_EMPTY,
	/*  27  */ SYMBOL_EMPTY,
	/*  28  */ SYMBOL_EMPTY,
	/*  29  */ SYMBOL_EMPTY,
	/*  30  */ SYMBOL_EMPTY,
	/*  31  */ SYMBOL_EMPTY,
	/*  32   */ SYMBOL_EMPTY,
	/*  33 ! */ SYMBOL_EMPTY,
	/*  34 " */ SYMBOL_EMPTY,
	/*  35 # */ SYMBOL_EMPTY,
	/*  36 $ */ SYMBOL_EMPTY,
	/*  37 % */ SYMBOL_EMPTY,
	/*  38 & */ SYMBOL_EMPTY,
	/*  39 ' */ SYMBOL_EMPTY,
	/*  40 ( */ SYMBOL_EMPTY,
	/*  41 ) */ SYMBOL_EMPTY,
	/*  42 * */ SYMBOL_EMPTY,
	/*  43 + */ SYMBOL_EMPTY,
	/*  44 , */ SYMBOL_EMPTY,
	/*  45 - */ SYMBOL_MINUS,
	/*  46 . */ SYMBOL_DOT,
	/*  47 / */ SYMBOL_EMPTY,
	/*  48 0 */ SYMBOL_0,
	/*  49 1 */ SYMBOL_1,
	/*  50 2 */ SYMBOL_2,
	/*  51 3 */ SYMBOL_3,
	/*  52 4 */ SYMBOL_4,
	/*  53 5 */ SYMBOL_5,
	/*  54 6 */ SYMBOL_6,
	/*  55 7 */ SYMBOL_7,
	/*  56 8 */ SYMBOL_8,
	/*  57 9 */ SYMBOL_9,
	/*  58 : */ SYMBOL_EMPTY,
	/*  59 ; */ SYMBOL_EMPTY,
	/*  60 < */ SYMBOL_EMPTY,
	/*  61 = */ SYMBOL_EMPTY,
	/*  62 > */ SYMBOL_EMPTY,
	/*  63 ? */ SYMBOL_EMPTY,
	/*  64 @ */ SYMBOL_EMPTY,
	/*  65 A */ SYMBOL_A,
	/*  66 B */ SYMBOL_B,
	/*  67 C */ SYMBOL_C,
	/*  68 D */ SYMBOL_D,
	/*  69 E */ SYMBOL_E,
	/*  70 F */ SYMBOL_F,
	/*  71 G */ SYMBOL_EMPTY,
	/*  72 H */ SYMBOL_H,
	/*  73 I */ SYMBOL_EMPTY,
	/*  74 J */ SYMBOL_EMPTY,
	/*  75 K */ SYMBOL_EMPTY,
	/*  76 L */ SYMBOL_L,
	/*  77 M */ SYMBOL_EMPTY,
	/*  78 N */ SYMBOL_EMPTY,
	/*  79 O */ SYMBOL_EMPTY,
	/*  80 P */ SYMBOL_P,
	/*  81 Q */ SYMBOL_EMPTY,
	/*  82 R */ SYMBOL_R,
	/*  83 S */ SYMBOL_EMPTY,
	/*  84 T */ SYMBOL_T,
	/*  85 U */ SYMBOL_U,
	/*  86 V */ SYMBOL_EMPTY,
	/*  87 W */ SYMBOL_EMPTY,
	/*  88 X */ SYMBOL_EMPTY,
	/*  89 Y */ SYMBOL_Y,
	/*  90 Z */ SYMBOL_EMPTY,
	/*  91 [ */ SYMBOL_EMPTY,
	/*  92 \ */ SYMBOL_EMPTY,
	/*  93 ] */ SYMBOL_EMPTY,
	/*  94 ^ */ SYMBOL_EMPTY,
	/*  95 _ */ SYMBOL_EMPTY,
	/*  96 ` */ SYMBOL_EMPTY,
	/*  97 a */ SYMBOL_EMPTY,
	/*  98 b */ SYMBOL_EMPTY,
	/*  99 c */ SYMBOL_EMPTY,
	/* 100 d */ SYMBOL_EMPTY,
	/* 101 e */ SYMBOL_EMPTY,
	/* 102 f */ SYMBOL_EMPTY,
	/* 103 g */ SYMBOL_EMPTY,
	/* 104 h */ SYMBOL_EMPTY,
	/* 105 i */ SYMBOL_EMPTY,
	/* 106 j */ SYMBOL_EMPTY,
	/* 107 k */ SYMBOL_EMPTY,
	/* 108 l */ SYMBOL_EMPTY,
	/* 109 m */ SYMBOL_EMPTY,
	/* 110 n */ SYMBOL_EMPTY,
	/* 111 o */ SYMBOL_EMPTY,
	/* 112 p */ SYMBOL_EMPTY,
	/* 113 q */ SYMBOL_EMPTY,
	/* 114 r */ SYMBOL_EMPTY,
	/* 115 s */ SYMBOL_EMPTY,
	/* 116 t */ SYMBOL_EMPTY,
	/* 117 u */ SYMBOL_EMPTY,
	/* 118 v */ SYMBOL_EMPTY,
	/* 119 w */ SYMBOL_EMPTY,
	/* 120 x */ SYMBOL_EMPTY,
	/* 121 y */ SYMBOL_EMPTY,
	/* 122 z */ SYMBOL_EMPTY,
	/* 123 { */ SYMBOL_EMPTY,
	/* 124 | */ SYMBOL_EMPTY,
	/* 125 } */ SYMBOL_EMPTY,
	/* 126 ~ */ SYMBOL_EMPTY,
	/* 127  */ SYMBOL_EMPTY,
};

#endif // ASCIISYMBOLMAP_H
