MODULE_COMMAND = $(notdir $(shell pwd))

SRCS = main.cpp

EXTRACXXFLAGS += -std=c++11 -DMODULE_COMMAND=${MODULE_COMMAND}
DEFAULT_VISIBILITY = protected

ifeq ($(BLUETOOTH21_DEBUG),yes)
EXTRACXXFLAGS += -DCONFIG_DEBUG_BLUETOOTH21
else ifneq ($(BLUETOOTH21_DEBUG),)
$(error Invalid BLUETOOTH21_DEBUG value: $(BLUETOOTH21_DEBUG))
endif
